id: I13E8E0BB
legacy_id: P009466
ocr_import_info:
  bdrc_scan_id: W23457
  source: bdrc
  ocr_info:
    timestamp: '2021-01-20T04:47:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:08:28.473724+00:00'
last_modified: 2022-09-02 09:08:49.437293
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23457
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23457
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞི་ཁྲོ་དགོངས་པ་ཀུན་འདུས་དང་མ་མོ་རྦོད་གཏོང་།
  author: རིག་འཛིན་ཀུན་གྲོལ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.650682278604311
  ocr_word_median_confidence_index: 0.68
quality: null
bases:
  I1956:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1956
      total_pages: 606
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1956.txt
    statistics:
      ocr_word_median_confidence_index: 0.69
      ocr_word_mean_confidence_index: 0.6589300260713874
    legacy_id: v001
  I1957:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1957
      total_pages: 380
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1957.txt
    statistics:
      ocr_word_median_confidence_index: 0.66
      ocr_word_mean_confidence_index: 0.6357023866705266
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
