id: I13E8E0BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:36:52+00:00'
last_modified: '2022-06-08T11:14:34.961238+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23457
  title: ཞི་ཁྲོ་དགོངས་པ་ཀུན་འདུས་དང་མ་མོ་རྦོད་གཏོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CD96:
      image_group_id: I1956
      title: ''
      total_pages: 606
      order: 1
      base_file: CD96.txt
    3CC3:
      image_group_id: I1957
      title: ''
      total_pages: 380
      order: 2
      base_file: 3CC3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
