id: P009466
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23457
  title: ཞི་ཁྲོ་དགོངས་པ་ཀུན་འདུས་དང་མ་མོ་རྦོད་གཏོང་།
  author: ''
  volumes:
    bbc70e467a2a420c8f96e1935f0d6c7a:
      image_group_id: I1956
      title: ''
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
    0c1f037e361c46249d204b3101a0ae04:
      image_group_id: I1957
      title: ''
      volume_number: 2
      total_pages: 380
      base_file: v002.txt
